name: release-plz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-plz:
    permissions:
      contents: write
      pull-requests: write
    uses: mythofmeat/repo-arch/.github/workflows/release-plz-rust.yml@main
    with:
      system_deps: "libasound2-dev"
    secrets: inherit
