name: release-plz

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    uses: mythofmeat/repo-arch/.github/workflows/release-plz-rust.yml@main
    with:
      system_deps: "libasound2-dev"
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
